//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LL1AnalyzerTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LL1AnalyzerTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S begin BODY end
        ///BODY ROW TAIL
        ///TAIL semicolon ROW TAIL
        ///TAIL #
        ///ROW VARS colon TYPE
        ///VARS identifier REST
        ///REST comma identifier REST
        ///REST #
        ///TYPE char
        ///TYPE boolean
        ///TYPE real
        ///TYPE integer.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a c
        ///a c
        ///c
        ///terminator
        ///a
        ///a c
        ///a
        ///c
        ///c
        ///b
        ///c
        ///d.
        /// </summary>
        internal static string set1 {
            get {
                return ResourceManager.GetString("set1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a
        ///b c.
        /// </summary>
        internal static string set2 {
            get {
                return ResourceManager.GetString("set2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///b
        ///a
        ///a
        ///b
        ///b.
        /// </summary>
        internal static string set3 {
            get {
                return ResourceManager.GetString("set3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///b
        ///a
        ///c
        ///a
        ///a.
        /// </summary>
        internal static string set4 {
            get {
                return ResourceManager.GetString("set4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a b c e
        ///d
        ///a
        ///e
        ///b c
        ///c
        ///b d terminator.
        /// </summary>
        internal static string set5 {
            get {
                return ResourceManager.GetString("set5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S A B C
        ///A D E
        ///B F G
        ///C #
        ///D a
        ///D #
        ///E a a
        ///E #
        ///F H K
        ///G b b
        ///H c c
        ///K d d.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S a S b
        ///S a S c
        ///S #.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S A
        ///S B
        ///A a A
        ///A a
        ///B b B
        ///B b.
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S a B A
        ///S b B bA
        ///A a b A
        ///A c
        ///B a
        ///B a b.
        /// </summary>
        internal static string test4 {
            get {
                return ResourceManager.GetString("test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S A b B
        ///S d
        ///A a A b
        ///A e d A b
        ///A B
        ///B c S d
        ///B #.
        /// </summary>
        internal static string test5 {
            get {
                return ResourceManager.GetString("test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S HEADER BLOCK
        ///HEADER program
        ///BLOCK TYPES VARS OPERATORS
        ///TYPES #
        ///TYPES type
        ///VARS #
        ///OPERATORS #.
        /// </summary>
        internal static string V50simplified {
            get {
                return ResourceManager.GetString("V50simplified", resourceCulture);
            }
        }
    }
}
