//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LL1ParserTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LL1ParserTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S COMPLEX_OPERATOR
        ///COMPLEX_OPERATOR begin OPERATOR OPERATOR_TAIL end
        ///OPERATOR_TAIL #
        ///OPERATOR_TAIL semicolon OPERATOR OPERATOR_TAIL
        ///OPERATOR ASSIGN_OPERATOR 
        ///OPERATOR CONDITIONAL_OPERATOR 
        ///OPERATOR COMPLEX_OPERATOR
        ///ASSIGN_OPERATOR VAR assign EXPRESSION
        ///CONDITIONAL_OPERATOR if EXPRESSION then COMPLEX_OPERATOR ELSE_TAIL
        ///ELSE_TAIL else OPERATOR
        ///ELSE_TAIL #
        ///VAR identifier VAR_TAIL
        ///VAR_TAIL point identifier VAR_TAIL
        ///VAR_TAIL #
        ///EXPRESSION SIMPLE_EXPR TAIL_EXPRESSION
        ///TAIL_EXPRESSION equality_op SIMP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _operator {
            get {
                return ResourceManager.GetString("_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  5.0.
        /// </summary>
        internal static string expr0 {
            get {
                return ResourceManager.GetString("expr0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+ident.
        /// </summary>
        internal static string expr1 {
            get {
                return ResourceManager.GetString("expr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+.
        /// </summary>
        internal static string expr2 {
            get {
                return ResourceManager.GetString("expr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // test 3
        ///(f / 3) * 3
        ///.
        /// </summary>
        internal static string expr3 {
            get {
                return ResourceManager.GetString("expr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 + var2&gt; 4 + ident * 3.
        /// </summary>
        internal static string expr4 {
            get {
                return ResourceManager.GetString("expr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (var1 * var3)+ 57.0 &gt; var2 * 7e9 + var3 * 8.2e-6 * 9.
        /// </summary>
        internal static string expr5 {
            get {
                return ResourceManager.GetString("expr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1*7 + 8*9* + 3*var5.
        /// </summary>
        internal static string expr6 {
            get {
                return ResourceManager.GetString("expr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S EXPRESSION
        ///EXPRESSION SIMPLE_EXPR TAIL_EXPRESSION
        ///TAIL_EXPRESSION equality_op SIMPLE_EXPR
        ///TAIL_EXPRESSION equality SIMPLE_EXPR
        ///TAIL_EXPRESSION #
        ///SIMPLE_EXPR SUMMAND TAIL_SUMMAND
        ///TAIL_SUMMAND add_op SUMMAND TAIL_SUMMAND
        ///TAIL_SUMMAND #
        ///SUMMAND MULTIPLIER TAIL
        ///TAIL mult_op MULTIPLIER TAIL
        ///TAIL #
        ///MULTIPLIER identifier 
        ///MULTIPLIER number 
        ///MULTIPLIER left_parenthesis EXPRESSION right_parenthesis
        ///MULTIPLIER not MULTIPLIER.
        /// </summary>
        internal static string expression {
            get {
                return ResourceManager.GetString("expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        ///  var1.field := 5*4
        ///end.
        /// </summary>
        internal static string operator0 {
            get {
                return ResourceManager.GetString("operator0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator1.txt
        ///begin
        ///var f:=4*5+2
        ///end.
        /// </summary>
        internal static string operator1 {
            get {
                return ResourceManager.GetString("operator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        ///  a:=5+3*3*8;
        ///  if b&gt;0 then
        ///  begin
        ///    a:=f;
        ///    f:=5
        ///  end
        ///end.
        /// </summary>
        internal static string operator2 {
            get {
                return ResourceManager.GetString("operator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        /// f:=5.3E10;
        /// if  (b + 1) &gt; (c - 2) then
        ///  begin
        ///    f.age:=g;
        ///    r:=7 * 2;
        ///    t:=5 + 6 - 7
        ///  end
        ///end.
        /// </summary>
        internal static string operator3 {
            get {
                return ResourceManager.GetString("operator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        /// a:=d and f;
        /// if a&gt;r then 
        /// if b&gt;t then
        /// begin
        ///  s:=4;
        ///  n:=n/4
        /// end
        ///end .
        /// </summary>
        internal static string operator4 {
            get {
                return ResourceManager.GetString("operator4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        /// if g&lt;&gt;5.4E10 then
        /// begin
        ///  p:=p*6;
        ///  if t=5 then
        ///  begin
        ///    p:=h+3
        ///  end
        /// end
        ///end
        ///   
        ///    .
        /// </summary>
        internal static string operator5 {
            get {
                return ResourceManager.GetString("operator5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        ///  if s+e&gt;5 then 
        ///  begin
        ///    f:=9;
        ///    r:=s - t
        ///  end;
        ///
        ///  begin
        ///    d:=8+9*s*t
        ///  end
        ///end.
        /// </summary>
        internal static string operator6 {
            get {
                return ResourceManager.GetString("operator6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S HEADER BLOCK point
        ///HEADER program identifier left_parenthesis FILENAME FILENAME_TAIL right_parenthesis semicolon
        ///FILENAME_TAIL comma FILENAME
        ///FILENAME_TAIL #
        ///FILENAME identifier point identifier
        ///BLOCK TYPE_DIVISION VARS_DIVISION OPERATOR_DIVISION
        ///
        ///TYPE_DIVISION #
        ///TYPE_DIVISION type TYPE_DEFINITION TYPE_DEFINITION_TAIL
        ///TYPE_DEFINITION_TAIL TYPE_DEFINITION TYPE_DEFINITION_TAIL
        ///TYPE_DEFINITION_TAIL #
        ///TYPE_DEFINITION identifier equality TYPE semicolon
        ///TYPE identifier 
        ///TYPE number two_points numbe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program test(file1.txt, file2.txt);
        ///begin
        ///  x := 5
        ///end..
        /// </summary>
        internal static string program0 {
            get {
                return ResourceManager.GetString("program0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program test(test.pro);
        ///
        ///type 
        ///tpoint = record
        ///  x,y: integer
        ///end;
        ///trange = integer;
        ///
        ///var x, y:integer;
        ///  z, t:boolean;
        ///  
        ///begin
        ///  x := 5;
        ///  y:=7
        ///  
        ///end..
        /// </summary>
        internal static string program1 {
            get {
                return ResourceManager.GetString("program1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program test(test.pro);
        ///
        ///type 
        ///trange = integer;
        ///ttest = boolean;
        ///ttest3 = real;
        ///
        ///begin
        ///  x := 5;
        ///  y:=7
        ///  
        ///end..
        /// </summary>
        internal static string program2 {
            get {
                return ResourceManager.GetString("program2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S record BODY end
        ///BODY ROW TAIL
        ///TAIL semicolon ROW TAIL
        ///TAIL #
        ///ROW VARS colon TYPE
        ///VARS identifier REST
        ///REST comma identifier REST
        ///REST #
        ///TYPE char
        ///TYPE integer
        ///TYPE real
        ///TYPE boolean.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1: integer;
        ///field3,field4: char;
        ///field3,field4, field5: real
        ///end.
        /// </summary>
        internal static string record0 {
            get {
                return ResourceManager.GetString("record0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1, field5:boolean;
        ///field3,field4:integer
        ///end.
        /// </summary>
        internal static string record1 {
            get {
                return ResourceManager.GetString("record1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean;
        ///field3,field4:integer
        ///end end.
        /// </summary>
        internal static string record2 {
            get {
                return ResourceManager.GetString("record2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean;
        ///field3,field4:integer
        ///end 
        ///end.
        /// </summary>
        internal static string record3 {
            get {
                return ResourceManager.GetString("record3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean;
        ///field3,field4:integer
        ///.
        /// </summary>
        internal static string record4 {
            get {
                return ResourceManager.GetString("record4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field1:boolean;
        ///field3,field4:integer
        ///end.
        /// </summary>
        internal static string record5 {
            get {
                return ResourceManager.GetString("record5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean;
        ///end.
        /// </summary>
        internal static string record6 {
            get {
                return ResourceManager.GetString("record6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean
        ///field3,field4:integer
        ///end.
        /// </summary>
        internal static string record7 {
            get {
                return ResourceManager.GetString("record7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1:boolean
        ///end.
        /// </summary>
        internal static string record8 {
            get {
                return ResourceManager.GetString("record8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record
        ///field1: integer;
        ///field3 nightmare
        ///field3,field4, field5: real
        ///end.
        /// </summary>
        internal static string record9 {
            get {
                return ResourceManager.GetString("record9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S TYPE_CHAPTER
        ///TYPE_CHAPTER #
        ///TYPE_CHAPTER type TYPE_DEFINITION TYPE_DEFINITION_TAIL
        ///TYPE_DEFINITION_TAIL TYPE_DEFINITION TYPE_DEFINITION_TAIL
        ///TYPE_DEFINITION_TAIL #
        ///TYPE_DEFINITION identifier equals TYPE semicolon
        ///TYPE identifier 
        ///TYPE number two_points number
        ///TYPE char
        ///TYPE integer
        ///TYPE real
        ///TYPE boolean.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S VARS_CHAPTER
        ///VARS_CHAPTER #
        ///VARS_CHAPTER var VAR_DEFINITION VAR_DEFINITION_TAIL
        ///VAR_DEFINITION_TAIL VAR_DEFINITION
        ///VAR_DEFINITION_TAIL #
        ///VAR_DEFINITION identifier IDENT_TAIL colon TYPE semicolon
        ///IDENT_TAIL #
        ///IDENT_TAIL comma identifier
        ///TYPE char
        ///TYPE integer
        ///TYPE real
        ///TYPE boolean.
        /// </summary>
        internal static string var {
            get {
                return ResourceManager.GetString("var", resourceCulture);
            }
        }
    }
}
